// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqk53D-hfkVpHIawM3m2WL3_QINnQdkUs',
    appId: '1:344504725295:web:76a7c0e34729c340c43bda',
    messagingSenderId: '344504725295',
    projectId: 'epark-mobile-52539',
    authDomain: 'epark-mobile-52539.firebaseapp.com',
    databaseURL: 'https://epark-mobile-52539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epark-mobile-52539.firebasestorage.app',
    measurementId: 'G-FFPRTE7JZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADeAI3SbSifViIs1G9_UUEZYN0iMZZ1T4',
    appId: '1:344504725295:android:94896b18741eefffc43bda',
    messagingSenderId: '344504725295',
    projectId: 'epark-mobile-52539',
    databaseURL: 'https://epark-mobile-52539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epark-mobile-52539.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-aOQRDZfk2pAfzOYSCUiw3EL7IZuuXnw',
    appId: '1:344504725295:ios:97bfb60d393f5c56c43bda',
    messagingSenderId: '344504725295',
    projectId: 'epark-mobile-52539',
    databaseURL: 'https://epark-mobile-52539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epark-mobile-52539.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-aOQRDZfk2pAfzOYSCUiw3EL7IZuuXnw',
    appId: '1:344504725295:ios:97bfb60d393f5c56c43bda',
    messagingSenderId: '344504725295',
    projectId: 'epark-mobile-52539',
    databaseURL: 'https://epark-mobile-52539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epark-mobile-52539.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqk53D-hfkVpHIawM3m2WL3_QINnQdkUs',
    appId: '1:344504725295:web:8d69ffff470e6494c43bda',
    messagingSenderId: '344504725295',
    projectId: 'epark-mobile-52539',
    authDomain: 'epark-mobile-52539.firebaseapp.com',
    databaseURL: 'https://epark-mobile-52539-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'epark-mobile-52539.firebasestorage.app',
    measurementId: 'G-6X4BXFEB52',
  );
}
